views/edit_profile.py
from flask_login import LoginManager, login_user, current_user, logout_user, login_required
from flask import render_template, Blueprint, current_app, request, redirect, url_for, flash

from werkzeug.utils import secure_filename
from werkzeug.security import generate_password_hash

import views.utils as utils
from models import User, Category, Post, Question, Answer, Vote, db

import os, glob

edit_profile_blueprint =  Blueprint('edit_profile_blueprint', __name__)

ALLOWED_EXTENSIONS = {'jpg'}

@edit_profile_blueprint.route("/edit_profile/")
@login_required
def edit_profile():
    return render_template('edit_profile.html', data=utils.get_base_data())

@edit_profile_blueprint.route("/edit_profile/", methods=['POST'])
@login_required
def edit_profile_post():
    name = request.form.get('name')
    email = request.form.get('email')
    password = request.form.get('password')
    description = request.form.get('description')

    if name: current_user.name = name
    
    if email:
        if User.query.filter_by(email=email).first():
            flash('User with this email already exists, choose different email.', 'error')
            return redirect(url_for('edit_profile_blueprint.edit_profile'))
        current_user.email = email
    
    if password: current_user.password = generate_password_hash(password)
    if description: current_user.description = description

    db.session.commit()

    picture = request.files['profile_picture']
    if picture and picture.filename:
        if not allowed_file(picture.filename):
            flash('Only .jpg images are supported.', 'error')
            return redirect(url_for('edit_profile_blueprint.edit_profile'))

        # remove old picture
        for filename in glob.glob(f"{current_app.config['UPLOAD_FOLDER']}/{current_user.id}.*"):
            os.remove(filename) 

        # save new picture
        filename = secure_filename(picture.filename)
        picture.save(f"{current_app.config['UPLOAD_FOLDER']}/{current_user.id}.{get_extension(filename)}")

    
    flash('Changes successfully applied.', 'info')
    return redirect(url_for('user_profile_blueprint.user_profile', user_id=current_user.id))


def get_extension(filename):
    return filename.rsplit('.', 1)[1].lower() 


def allowed_file(filename):
    """
        Checks whether filename has allowed extension
    """
    return '.' in filename and \
           get_extension(filename) in ALLOWED_EXTENSIONS

views/home.py
from flask import render_template, Blueprint, request

from models import User, Category, Post, Question, Answer, Vote, db
import views.utils as utils

home_blueprint =  Blueprint('home_blueprint', __name__)

@home_blueprint.route("/home/", methods=['GET', 'POST'])
def home():
    data = utils.get_base_data()
    categories_data = []
    categories = db.session.query(Category).all()

    for category in categories:
        questions = db.session.query(Question).filter_by(category_id = category.id)
        last_question = questions.order_by(Question.date.desc()).first()
        categories_data.append({
            'category': category,
            'questions_count': questions.count(),
            'last_question': last_question,
            'last_question_author_name': last_question.author.name if last_question else '',
            'last_question_date': last_question.date.strftime('%d/%m/%y, %H:%M') if last_question else ''
        })

    data['categories_data'] = categories_data
    data['mode'] = 'categories'

    return render_template(
        'index.html', 
        data=data
    )


@home_blueprint.route("/category/")
def category(): 
    category = db.session.query(Category).filter_by(id = int(request.args.get('category_id'))).first()
    questions = db.session.query(Question).filter_by(category_id = category.id).order_by(Question.date.desc())

    data = utils.get_base_data()
    data['mode'] = 'questions'
    data['category_name'] = category.name
    data['questions_data'] = utils.get_questions_data(questions)
    data['category'] = category

    return render_template(
        'index.html', 
        data = data
    )

views/log_in.py
from flask import url_for, render_template, Blueprint, current_app, redirect, request, flash
from flask_login import login_user, logout_user, login_required

from werkzeug.security import check_password_hash

from models import User, db
import views.utils as utils

log_in_blueprint = Blueprint('log_in_blueprint', __name__)

@log_in_blueprint.route("/log_in/")
def log_in():
    return render_template('log_in.html', data=utils.get_base_data())


@log_in_blueprint.route("/log_in/", methods=['POST'])
def log_in_post():
    email = request.form.get('email')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first()
    if user and check_password_hash(user.password, password):
        login_user(user)
        return redirect(url_for('home_blueprint.home'))

    flash('Wrong email or password.', 'error')
    return redirect(url_for('log_in_blueprint.log_in'))


@log_in_blueprint.route("/log_out/")
@login_required
def log_out():
    logout_user()
    return redirect(url_for('home_blueprint.home'))

views/new_question.py
from flask import render_template, request, url_for, redirect, Blueprint, flash
from flask_login import login_required, current_user
import datetime

import views.utils as utils
from models import Category, Question, db

new_question_blueprint =  Blueprint('new_question_blueprint', __name__)


@new_question_blueprint.route("/new_question/")
@login_required
def new_question():
    data = utils.get_base_data()
    data['category_id'] = request.args.get('category_id')
    return render_template('new_question.html', data=data)


@new_question_blueprint.route("/new_question/", methods=['POST'])
@login_required
def new_question_post():

    title = request.form.get('title')
    content = request.form.get('content')

    if not content or not title:
        flash('Content and title cannot be empty.', 'error')
        return redirect(url_for('new_question_blueprint.new_question'))


    question = Question()
    question.author_id = current_user.id
    question.content = content
    question.date = datetime.datetime.now()
    question.title = title
    question.category_id = Category.query.filter_by(name=request.form.get('category_id')).first().id

    db.session.add(question)       
    db.session.commit()

    return redirect(url_for('question_blueprint.question', question_id=question.id))

views/profile.py
from flask import render_template, request, Blueprint

import views.utils as utils
from models import User, Category, Post, Question, Answer, Vote, db

user_profile_blueprint =  Blueprint('user_profile_blueprint', __name__)

@user_profile_blueprint.route("/user_profile/")
def user_profile():
    data = utils.get_base_data()
    data['user_id'] = request.args.get('user_id')
    data['user'] = User.query.filter_by(id=int(data['user_id'])).first()

    answers = Answer.query.filter_by(author_id=int(data['user_id']))
    questions = Question.query.filter_by(author_id=int(data['user_id']))

    data['answers_data'] = utils.get_answers_data(answers)
    data['questions_data'] = utils.get_questions_data(questions)

    return render_template(
        'profile.html',
        data=data
    )

views/question.py
from flask import jsonify, render_template, request, url_for, redirect, flash, Blueprint
from flask_login import current_user
from flask_login import login_required
import datetime

from models import User, Category, Post, Question, Answer, Vote, db
import views.utils as utils

question_blueprint =  Blueprint('question_blueprint', __name__)

@question_blueprint.route("/question/")
def question():
    question = db.session.query(Question).filter_by(id = int(request.args.get('question_id'))).first()
    answers = db.session.query(Answer).filter_by(question_id = question.id)

    question_data = utils.get_questions_data([question])[0]
    answers_data = utils.get_answers_data(answers)

    data = utils.get_base_data()
    data['question_data'] = question_data
    data['answers_data'] = answers_data
    data['category'] = db.session.query(Category).filter_by(id = question.category_id).first()
    data['has_best'] = answers.filter_by(is_best=True).first() != None

    # parameter from profile page to automatically hover over selected answer
    if 'answer_id' in request.args:
        answer_id = int(request.args.get('answer_id'))
        data['answer_id'] = answer_id

    return render_template(
        'question.html', 
        data = data
    )


@question_blueprint.route("/question/", methods=['POST'])
def question_post():
    question_id = int(request.form.get('question_id'))
    content = request.form.get('answer')

    if not content:
        flash('Answer cannot be empty.', 'error')
        return redirect(url_for('question_blueprint.question', question_id=question_id))

    answer = Answer()
    answer.question_id = question_id
    answer.is_best = False
    answer.author_id = current_user.id
    answer.content = content
    answer.date = datetime.datetime.now()

    db.session.add(answer)       
    db.session.commit()

    flash('Successfully added new answer.', 'info')
    return redirect(url_for('question_blueprint.question', question_id=question_id))


@question_blueprint.route("/vote")
@login_required
def vote():
    post_id = request.args.get('post_id')
    is_up = request.args.get('up') == '1'

    # check if its not current user post
    post = Post.query.filter_by(id=post_id).first()
    if post.author_id == current_user.id:
        return jsonify(result="#1")

    # check if user voted this post earlier
    vote = Vote.query.filter_by(post_id=post_id, author_id=current_user.id).first()
    if vote:
        return jsonify(result="#2")

    vote = Vote()
    vote.post_id = post_id
    vote.author_id = current_user.id
    vote.is_up = is_up

    db.session.add(vote)       
    db.session.commit()

    votes_up = post.votes.filter_by(is_up = True).count()
    votes_down = post.votes.filter_by(is_up = False).count()
    votes_sum = votes_up - votes_down

    return jsonify(result=votes_sum)


@question_blueprint.route("/mark_best")
def mark_best():
    answer_id = request.args.get('answer_id')

    answer = Answer.query.filter_by(id=answer_id).first()
    answer.is_best = True

    db.session.commit()

    flash('Successfully marked answer as best.', 'info')
    return redirect(url_for('question_blueprint.question', question_id=answer.question_id))

views/sign_up.py
from flask import render_template, Blueprint, current_app, url_for, redirect, request, flash
from flask_login import login_user
from werkzeug.security import generate_password_hash
import datetime
import shutil

from models import User, db
import views.utils as utils

sign_up_blueprint = Blueprint('sign_up_blueprint', __name__)

@sign_up_blueprint.route("/sign_up/")
def sign_up():
    return render_template('sign_up.html', data=utils.get_base_data())


@sign_up_blueprint.route("/sign_up/", methods=['POST'])
def sign_up_post():

    name = request.form.get('name')
    email = request.form.get('email')
    password = request.form.get('password')

    if not (name and email and password):
        flash('You must fill all data.', 'error')
        return redirect(url_for('sign_up_blueprint.sign_up'))       

    if User.query.filter_by(email=email).first():
        flash('User with this email already exists, choose different email.', 'error')
        return redirect(url_for('sign_up_blueprint.sign_up'))

    user = User()
    user.email = email
    user.name = name
    user.password = generate_password_hash(password)
    user.join_date = datetime.datetime.now()

    db.session.add(user)       
    db.session.commit()

    login_user(user)

    shutil.copy(f"{current_app.config['UPLOAD_FOLDER']}/unknown.jpg", f"{current_app.config['UPLOAD_FOLDER']}/{user.id}.jpg")

    flash('Successfully created new account, you can now vote, answer questions and ask own.', 'info')
    return redirect(url_for('home_blueprint.home'))

templates/base.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>Flask Forum</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/styles/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>    
</head>
    <body class="bg-secondary" style="height: 100%; width: 100%;">

        <div class="container-fluid" style="width: 60%; margin:auto">
            <div class="d-flex flex-row bg-dark p-3 my-2">
                <div class="d-flex mr-auto">
                    <h2 class="p-2" style="color:white">
                        <a href="/home/">Flask Forum</a>
                    
                        {% if data.category %}
                        - <a href="{{url_for('home_blueprint.category', category_id=data.category.id)}}">{{data.category.name}}</a>
                        {% endif %}
                    </h2>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item active">
                                <a class="nav-link" href="/">Categories <span class="sr-only">(current)</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="d-flex">
                    {%if data.logged_user_id != -1 %}

                    <div class="btn-group">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="/static/profiles/{{data.logged_user_id}}.jpg" height="48" width="48"/>
                        </button>
                        <div class="dropdown-menu dropdown-menu-right my-2 my-lg-0" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{{url_for('user_profile_blueprint.user_profile', user_id=data.logged_user_id)}}">My Profile</a>
                            <a class="dropdown-item" href="{{url_for('log_in_blueprint.log_out')}}">Log Off</a>
                        </div>
                    </div>

                    {% else %}
                    <a href="{{url_for('log_in_blueprint.log_in')}}"><input type="submit" class="btn btn-primary mr-1 mt-3 btn-sm" value="Log In"></input></a>
                    <a href="{{url_for('sign_up_blueprint.sign_up')}}"><input type="submit" class="btn btn-info mt-3 btn-sm" value="Sign up"></input></a>
                    {% endif %} 
                </div>
            </div>           
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                    <div class="d-flex bg-dark p-2" style="border-left: 7px solid {% if category == 'error' %} brown {% else %} green {% endif %}">
                        <p 
                        {% if category == 'error' %} 
                            style="color:orangered"
                        {% else %}
                            style="color:rgb(2, 148, 58)"
                        {% endif %}
                        >{{ message }}</p>
                    </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            <div class="d-flex flex-row my-2" style="color: white;">
                <div class="d-flex" style="width:100%;">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            
        </div>
    </body>
</html>

templates/edit_profile.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex flex-column" style="width: 100%;">
    <div class="bg-dark p-4" style="color: white">
        <h2>
            Edit Profile
        </h2>
        <form method="POST" action="/edit_profile/" enctype="multipart/form-data">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="name" class="form-control" name="name" placeholder="Enter new name or leave empty">
            </div>
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" name="email" placeholder="Enter new email or leave empty">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" placeholder="Enter new password or leave empty">
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <textarea name="description" class="form-control" rows="3" placeholder="Enter new description or leave empty"></textarea>
            </div>
            <div class="form-group">
                <label for="profile_picture">Profile Picture (.jpg only)</label><br>
                <input type="file" name="profile_picture">
            </div>
            <button type="submit" class="btn btn-primary btn-block">Save Changes</button>
        </form>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex flex-column  bg-dark" style="width: 100%;">
    <div class="d-flex p-3">
        <h2>
            {% if data.mode == 'categories' %} Categories {% else %} Questions in category: {{data.category_name}} {% endif %}
        </h2>
    </div>
    <div>
        <div class="p-1">
            <ul class="list-group">
                {% if data.mode == 'categories' %}
                    {% for category_data in data.categories_data %}
                        <li class="list-group-item text-light m-2" style="background-color: rgb(53, 53, 53);">                         
                                <h5>
                                    <a href="{{url_for('home_blueprint.category', category_id=category_data.category.id)}}">{{category_data.category.name}}</a> 
                                    - {{category_data.questions_count}} Questions
                                </h5>                           
                            <p class="small">
                                {{category_data.category.description}}<br>
                                {% if category_data.last_question %}
                                Last Question: 
                                    <a href="{{url_for('question_blueprint.question', question_id=category_data.last_question.id)}}">{{category_data.last_question.title}}</a>
                                    by <a href="{{url_for('user_profile_blueprint.user_profile', user_id=category_data.last_question.author_id)}}">{{category_data.last_question_author_name}}</a>, {{category_data.last_question_date}}
                                {% endif %}
                            </p>                        
                        </li>
                    {% endfor %}
                {% else %}
                    {% for question_data in data.questions_data%}
                        <li class="list-group-item text-light m-2" style="background-color: rgb(53, 53, 53); {% if question_data.has_best %} border-left: 10px solid rgb(31, 255, 31) {% endif %}">
                            <p class="votes_text">                
                            {%if question_data.votes_sum > 0 %} 
                                +{{question_data.votes_sum}} 
                            {% else %} 
                                {{question_data.votes_sum}} 
                            {% endif %}, {{question_data.answers_count}} answers</p>
                            <a href="{{url_for('question_blueprint.question', question_id=question_data.question.id)}}">
                                <p class="question_title_text ml-3">{{question_data.question.title}}</p>
                            </a>
                            <p class="question_author_text">asked {{question_data.time}} by <a href="{{url_for('user_profile_blueprint.user_profile', user_id=question_data.question.author_id)}}">{{question_data.author_name}}</a></p>
                        </li>
                    {% endfor %}
                {% endif %}
            </ul>

            {% if data.mode == 'questions' %}
            <div class="mt-4 mx-2" style="border-bottom: 1px solid rgb(73, 73, 73);"></div>
            {% endif %}
        </div>

        {% if data.mode == 'questions' %}
            {%if data.logged_user_id != -1 %}
            <div class="p-3 mt-2">
                <a href="{{url_for('new_question_blueprint.new_question', category_id=data.category_name)}}"><button type="button" class="btn btn-primary btn-block">Ask New Question</button></a>
            </div>
            {% else %}
            <div class="p-3 mt-2 text-center">
                <a href="{{url_for('log_in_blueprint.log_in')}}"><input type="submit" class="btn btn-primary mr-1 btn-sm" value="Log In"></input></a> Or
                <a href="{{url_for('sign_up_blueprint.sign_up')}}"><input type="submit" class="btn btn-info btn-sm" value="Sign up"></input></a> To ask new question
            </div>
            {% endif %}
        {% endif %}

    </div>
</div>


{% endblock %}

templates/log_in.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex flex-column bg-dark" style="width: 100%;">
    <div class="d-flex p-4">
        <h2>Log in</h2>
    </div>
    <div class="my-1 p-4" style="color: white">
        <form method="POST" action="/log_in/">
            <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" name="email" placeholder="Enter email">
            </div>
            <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary btn-block mt-5">Log In</button>
        </form>
    </div>
</div>
{% endblock %}

templates/new_question.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex flex-column" style="width: 100%;">
    <div class="bg-dark p-4">
        <h2>New Question</h2>
        <form method="POST" action="/new_question/" class="mt-5">
            <div class="d-flex">
                <h5>Title:</h5>
            </div>
            <div class="d-flex">
                <input type="text" class="form-control" name="title">
            </div>           
            <div class="d-flex mt-2">
                <h5>Content:</h5>
            </div>
            <div class="d-flex mt-2">
                <textarea name="content" class="form-control" rows="3"></textarea>
            </div>
            <div class="d-flex mt-4">
                <input type="submit" value="Submit" class="btn btn-primary btn-block"/>
            </div>
            <input type="hidden" name="category_id" value="{{data.category_id}}">
        </form>
    </div>
</div>


{% endblock %}

templates/question.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex flex-column" style="width: 100%;">
    <div class="header bg-dark">
        <div class="d-flex p-3">
            <h2>{{data.question_data.question.title}}</h2>
        </div>
        <div class="d-flex flex-row">
            <div class="p-4 text-center">
                {% if data.logged_user_id != -1 %}
                    <button type="button" class="btn btn-primary btn-sm vote_btn_up" id="{{data.question_data.question.id}}">↑</button>
                {% else %}
                    <a href="{{url_for('log_in_blueprint.log_in')}}"><button type="button" class="btn btn-primary btn-sm">↑</button></a>
                {% endif %}
                <h3  class="post_votes" id="{{data.question_data.question.id}}">
                    {%if data.question_data.votes_sum > 0 %} 
                    +{{data.question_data.votes_sum}} 
                    {% else %} 
                        {{data.question_data.votes_sum}} 
                    {% endif %}
                </h3>
                {% if data.logged_user_id != -1 %}
                    <button type="button" class="btn btn-primary btn-sm vote_btn_down" id="{{data.question_data.question.id}}">↓</button>
                {% else %}
                    <a href="{{url_for('log_in_blueprint.log_in')}}"><button type="button" class="btn btn-primary btn-sm">↓</button></a>
                {% endif %}
            </div>
            <div class="p-2 mx-4 p-3" style="width:100%; border-bottom: 1px solid rgb(73, 73, 73);">{{data.question_data.question.content}}</div>
        </div>
        <div class="d-flex p-3 justify-content-end">
            <div class="d-flex p-2">
                <p class="small">Asked {{data.question_data.time}} by <a href="{{url_for('user_profile_blueprint.user_profile', user_id=data.question_data.question.author_id)}}">{{data.question_data.author_name}}</a></p>
            </div>
            <div class="d-flex p-2">
                <img src="/static/profiles/{{data.question_data.question.author_id}}.jpg" height="64" width="64"/>
            </div>
        </div>
    </div>

    {% for answer_data in data.answers_data %}
    <div id="{{answer_data.answer.id}}" class="bg-dark my-2" style="color: white; {% if answer_data.answer.is_best %} border-left: 10px solid rgb(31, 255, 31) {% endif %}">
        <div class="d-flex flex-row">
            <div class="p-4 text-center">

                {% if not data.has_best and data.logged_user_id == data.question_data.question.author_id  %}                
                <a href="{{url_for('question_blueprint.mark_best', answer_id=answer_data.answer.id)}}"><button type="button" class="btn btn-success btn-sm my-3">✓</button></a>
                {% endif %}

                {% if answer_data.answer.is_best %}
                <a href="#"><button type="button" class="btn btn-success btn-sm my-3" disabled>✓</button></a>
                {% endif %}

                {% if data.logged_user_id != -1 %}
                    <button type="button" class="btn btn-primary btn-sm vote_btn_up" id="{{answer_data.answer.id}}">↑</button>
                {% else %}
                    <a href="{{url_for('log_in_blueprint.log_in')}}"><button type="button" class="btn btn-primary btn-sm">↑</button></a>
                {% endif %}
                <h3 class="post_votes" id="{{answer_data.answer.id}}">
                    {%if answer_data.votes_sum > 0 %} 
                    +{{answer_data.votes_sum}} 
                    {% else %} 
                        {{answer_data.votes_sum}} 
                    {% endif %}
                </h3>
                {% if data.logged_user_id != -1 %}
                    <button type="button" class="btn btn-primary btn-sm vote_btn_down" id="{{answer_data.answer.id}}">↓</button>
                {% else %}
                    <a href="{{url_for('log_in_blueprint.log_in')}}"><button type="button" class="btn btn-primary btn-sm">↓</button></a>
                {% endif %}
            </div>
            <div class="mx-4 p-3" style="width:100%; border-bottom: 1px solid rgb(73, 73, 73);">{{answer_data.answer.content}}</div>
        </div>
        <div class="d-flex p-3 justify-content-end">
            <div class="d-flex p-2">
                <p class="small">Answered {{answer_data.time}} By <a href="{{url_for('user_profile_blueprint.user_profile', user_id=answer_data.answer.author_id)}}">{{answer_data.answer.author.name}}</a></p>
            </div>
            <div class="d-flex p-2">
                <img src="/static/profiles/{{answer_data.answer.author_id}}.jpg" height="64" width="64"/>
            </div>
        </div>
    </div>
    {% endfor %}

    <div class="bg-dark my-2 p-4" style="color: white">
        {%if data.logged_user_id != -1 %}
        <form method="POST" action="/question/">
            <div class="d-flex">
                <h5>Write your answer:</h5>
            </div>
            <div class="d-flex mt-4">
                <textarea name="answer" class="form-control" rows="3"></textarea>
            </div>
            <div class="d-flex mt-4">
                <input type="submit" value="Answer" class="btn btn-primary btn-block"/>
            </div>
            <input type="hidden" name="question_id" value="{{data.question_data.question.id}}">
        </form>
        {% else %}
        <div class="p-2 mt-1 text-center">
            <a href="{{url_for('log_in_blueprint.log_in')}}"><input type="submit" class="btn btn-primary mr-1 btn-sm" value="Log In"></input></a> Or
            <a href="{{url_for('sign_up_blueprint.sign_up')}}"><input type="submit" class="btn btn-info btn-sm" value="Sign up"></input></a> To answer
        </div>
        {% endif %}
    </div>
</div>

<script type=text/javascript>
    $SCRIPT_ROOT = {{ request.script_root|tojson }};
    
    $('.vote_btn_up').click(function(){
        onVote($(this).attr('id'), 1);
    })

    $('.vote_btn_down').click(function() {
        onVote($(this).attr('id'), 0);       
    })
    
    function onVote(post_id, up){
        $.getJSON($SCRIPT_ROOT + '/vote', {
                post_id: post_id,
                up: up
            })
            .done(function(data){
                if(data.result == "#1")
                {
                    alert("You can't vote your own post");
                    return;
                }
                
                if(data.result == "#2")
                {
                    alert("You already voted this post");
                    return;
                }
                
                asInt = parseInt(data.result);
                $('#'+post_id+'.post_votes').text(asInt < 0 ? asInt.toString() : '+' + asInt.toString());
            });
    }

    {% if data.answer_id %}
    $(document).ready(function(){
        window.location.href = '#' + {{data.answer_id}};
    });
    {% endif %}

</script>

{% endblock %}